# Copyright 2025 whereabouts authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Dont'forget to update deployment/whereabouts-chart/templates/node-slice-controller.yaml as well
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereabouts-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereabouts-controller
  template:
    metadata:
      labels:
        app: whereabouts-controller
    spec:
      containers:
        - command:
            - /node-slice-controller
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: WHEREABOUTS_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: ghcr.io/k8snetworkplumbingwg/whereabouts:latest
          name: whereabouts
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cnibin
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /cron-schedule
              name: cron-scheduler-configmap
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-6kd6k
              readOnly: true
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: whereabouts
      serviceAccountName: whereabouts
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /opt/cni/bin
            type: ""
          name: cnibin
        - hostPath:
            path: /etc/cni/net.d
            type: ""
          name: cni-net-dir
        - configMap:
            defaultMode: 484
            items:
              - key: cron-expression
                path: config
            name: whereabouts-config
          name: cron-scheduler-configmap
        - name: kube-api-access-6kd6k
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace