# 2025 NVIDIA CORPORATION & AFFILIATES
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Fork Sync

on:
  schedule:
    - cron: '0 0 * * *' # nightly
  workflow_dispatch:    # enable manual trigger

jobs:
  call-reusable-sync-fork-workflow:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/fork-sync-reusable.yml@main
    with:
      upstream-owner: k8snetworkplumbingwg
      default-branch: master
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
